apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-openproject-pv001
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.31.10.4
    path: /nfs/openproject
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-openproject-claim1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
