apiVersion: v1
kind: Pod
metadata:
  name: openproject
  labels:
    name: openproject
spec:
  containers:
    - name: openproject
      image: openproject/community:7
      env:
        - name: DATABASE_URL
          value: "postgres://openproject:password@172.31.10.7:30432/openproject_db?pool=10&encoding=unicode&timeout=5000&reconnect=true"
        - name: SECRET_KEY_BASE
          value: longandcomprecetedsecret
        - name: CACHE_MEMCACHE_SERVER
          value: 172.31.10.16
        - name: CACHE_NAMESPACE
          value: openproject
      ports:
        - name: openproject
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/db/openproject
          name: data
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 600
        timeoutSeconds: 1
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nfs-openproject-claim1